package PetPals;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Register extends javax.swing.JFrame {

    PreparedStatement ps; ResultSet rs; User user = new User();
    
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    void register() {
        // Creating a new account
        user.setFirstname(suFirstName.getText());
        user.setLastname(suLastName.getText());
        user.setUsername(suUsername.getText());
        String role = (String) roleCB.getSelectedItem();
        user.setEmail(suEmail.getText());
        user.setPassword(String.valueOf(suPassword.getPassword()));
        
        if(user.getFirstname().equals("") || user.getFirstname().equals("Enter First Name")){
            JOptionPane.showMessageDialog(null, "Add a First Name.");
        }
        else if(user.getLastname().equals("") || user.getLastname().equals("Enter Last Name")){
            JOptionPane.showMessageDialog(null, "Add a Last Name.");
        }
        else if(user.getUsername().equals("") || user.getUsername().equals("Enter Username")){
            JOptionPane.showMessageDialog(null, "Add a Username.");
        }
        else if(user.getEmail().equals("") || user.getEmail().equals("Enter Email")){
            JOptionPane.showMessageDialog(null, "Add an Email.");
        }  
        else if(user.getPassword().equals("") || user.getPassword().equals("Enter Password")){
            JOptionPane.showMessageDialog(null, "Add a Password.");
        }
        else if(checkUsername(user.getUsername())){
             JOptionPane.showMessageDialog(null, "This Username already exist.");
        }
        else{
            try {
            ps = Database.connect().prepareStatement("INSERT INTO `users_table`(`Username`, `Password`, `UserEmail`, `UserFirstName`,`UserLastName`,`Role`) VALUES (?,?,?,?,?,?)");
            
            ps.setString(1, user.getUsername());
            ps.setString(2, user.getPassword());
            ps.setString(3, user.getEmail());
            ps.setString(4, user.getFirstname());
            ps.setString(5, user.getLastname());
            ps.setString(6, role);
             
             if (ps.executeUpdate() > 0){
                 JOptionPane.showMessageDialog(null, "New User Added");
             }
             
            suFirstName.setText("");
            suLastName.setText("");
            suUsername.setText("");
            roleCB.setSelectedItem(null);
            suEmail.setText("");
            suPassword.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }
    
    public boolean checkUsername(String username){
        // to check if there's already an existing username created.
        boolean checkUser = false;
         
        try {
            ps = Database.connect().prepareStatement("SELECT * FROM `users_table` WHERE `Username` = ?");
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkUser;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        suFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        suLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        suUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        suEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        suPassword = new javax.swing.JPasswordField();
        signupB = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        loginL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        roleCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetPals: Pet Adoption Management System");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/PetPalsLogo350.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(251, 203, 227));

        suFirstName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        suFirstName.setForeground(new java.awt.Color(153, 153, 153));
        suFirstName.setText("Enter First Name");
        suFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 134, 175), 2, true));
        suFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                suFirstNameFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 134, 175));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIGN UP");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 134, 175));
        jLabel3.setText("First Name");

        suLastName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        suLastName.setForeground(new java.awt.Color(153, 153, 153));
        suLastName.setText("Enter Last Name");
        suLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 134, 175), 2, true));
        suLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                suLastNameFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 134, 175));
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 134, 175));
        jLabel5.setText("Username");

        suUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        suUsername.setForeground(new java.awt.Color(153, 153, 153));
        suUsername.setText("Enter Username");
        suUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 134, 175), 2, true));
        suUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                suUsernameFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 134, 175));
        jLabel6.setText("Email");

        suEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        suEmail.setForeground(new java.awt.Color(153, 153, 153));
        suEmail.setText("Enter Email");
        suEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 134, 175), 2, true));
        suEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                suEmailFocusGained(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 134, 175));
        jLabel7.setText("Password");

        suPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        suPassword.setForeground(new java.awt.Color(153, 153, 153));
        suPassword.setText("Enter Password");
        suPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 134, 175), 2, true));
        suPassword.setEchoChar('•');
        suPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                suPasswordFocusGained(evt);
            }
        });

        signupB.setBackground(new java.awt.Color(238, 134, 175));
        signupB.setPreferredSize(new java.awt.Dimension(200, 35));
        signupB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupBMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sign Up");

        javax.swing.GroupLayout signupBLayout = new javax.swing.GroupLayout(signupB);
        signupB.setLayout(signupBLayout);
        signupBLayout.setHorizontalGroup(
            signupBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        signupBLayout.setVerticalGroup(
            signupBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        loginL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        loginL.setForeground(new java.awt.Color(238, 134, 175));
        loginL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginL.setText("Back to Login");
        loginL.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(238, 134, 175)));
        loginL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 134, 175));
        jLabel9.setText("Role");

        roleCB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        roleCB.setForeground(new java.awt.Color(153, 153, 153));
        roleCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        roleCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 134, 175), 2, true));
        roleCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roleCBFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signupB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(loginL)))
                .addGap(75, 75, 75))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(suUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(jLabel7)
                        .addComponent(suPassword)
                        .addComponent(roleCB, 0, 317, Short.MAX_VALUE)
                        .addComponent(suEmail)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(suFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(92, 92, 92))
                                .addComponent(suLastName)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleCB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginL)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBMouseClicked
        register();
    }//GEN-LAST:event_signupBMouseClicked

    private void loginLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLMouseClicked
        // TODO add your handling code here:
        dispose();
        Login login = new Login ();
        login.setVisible(true);
    }//GEN-LAST:event_loginLMouseClicked

    private void suFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_suFirstNameFocusGained
        // TODO add your handling code here:
        user.setFirstname(suFirstName.getText());
        if (user.getFirstname().equals("Enter First Name")){
            suFirstName.setText("");
            suFirstName.setForeground(new Color(238,134,175));
        }
    }//GEN-LAST:event_suFirstNameFocusGained

    private void suLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_suLastNameFocusGained
        // TODO add your handling code here:
        user.setLastname(suLastName.getText());
        if (user.getLastname().equals("Enter Last Name")) {
            suLastName.setText("");
            suLastName.setForeground(new Color(238,134,175));
        }
    }//GEN-LAST:event_suLastNameFocusGained

    private void suUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_suUsernameFocusGained
        // TODO add your handling code here:
        user.setUsername(suUsername.getText());
        if (user.getUsername().equals("Enter Username")) {
            suUsername.setText("");
            suUsername.setForeground(new Color(238,134,175));
        }
    }//GEN-LAST:event_suUsernameFocusGained

    private void suEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_suEmailFocusGained
        // TODO add your handling code here:
        user.setEmail(suEmail.getText());
        if (user.getEmail().equals("Enter Email")) {
            suEmail.setText("");
            suEmail.setForeground(new Color(238,134,175));
        }
    }//GEN-LAST:event_suEmailFocusGained

    private void suPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_suPasswordFocusGained
        // TODO add your handling code here:
        user.setPassword(String.valueOf(suPassword.getPassword()));
        if (user.getPassword().equals("Enter Password")) {
            suPassword.setText("");
            suPassword.requestFocus();
            suPassword.setEchoChar('•');
            suPassword.setForeground(new Color(238,134,175));
        }
    }//GEN-LAST:event_suPasswordFocusGained

    private void roleCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roleCBFocusGained
        // TODO add your handling code here:
        roleCB.setForeground(new Color(238,134,175));
    }//GEN-LAST:event_roleCBFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginL;
    private javax.swing.JComboBox<String> roleCB;
    private javax.swing.JPanel signupB;
    private javax.swing.JTextField suEmail;
    private javax.swing.JTextField suFirstName;
    private javax.swing.JTextField suLastName;
    private javax.swing.JPasswordField suPassword;
    private javax.swing.JTextField suUsername;
    // End of variables declaration//GEN-END:variables
}
